# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='osys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('os_bit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plugin_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_version_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='render_engien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_engien_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='render_engien_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renEngVer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50)),
                ('software_bit', models.CharField(max_length=50)),
                ('software_os', models.ManyToManyField(to='apiranch.osys')),
            ],
        ),
        migrations.CreateModel(
            name='softwareVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_version', models.CharField(max_length=50)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiranch.plugin')),
                ('render_engien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiranch.render_engien')),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='software_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiranch.softwareVersion'),
        ),
        migrations.AddField(
            model_name='render_engien',
            name='render_engien_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiranch.render_engien_version'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='plugin_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiranch.plugin_version'),
        ),
    ]
