# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiranch', '0002_auto_20190218_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareversion',
            name='plugin',
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='plugin',
            field=models.ManyToManyField(to='apiranch.plugin'),
        ),
    ]
