# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiranch', '0004_auto_20190218_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='plugin_version',
            field=models.ManyToManyField(to='apiranch.plugin_version'),
        ),
        migrations.AlterField(
            model_name='render_engien',
            name='render_engien_version',
            field=models.ManyToManyField(to='apiranch.render_engien_version'),
        ),
    ]
