# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiranch', '0005_auto_20190218_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='plugin_version',
            field=models.ManyToManyField(blank=True, to='apiranch.plugin_version'),
        ),
    ]
